<Project Sdk="Tomat.Terraria.ModLoader.Sdk/1.0.9">
  <PropertyGroup>
    <LangVersion>preview</LangVersion>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <DoNotPublicize Include="tModLoader:Terraria.Tile" />
    <Publicize Include="CalamityMod" />
    <Publicize Include="FNA" IncludeCompilerGeneratedMembers="false" IncludeVirtualMembers="false" />
    <Publicize Include="ReLogic" IncludeCompilerGeneratedMembers="false" IncludeVirtualMembers="false" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Content\NPCs\GrumpfishNPC\" />
  </ItemGroup>
</Project>