<Project Sdk="Tomat.Terraria.ModLoader.Sdk/2.1.1">
  <PropertyGroup>
    <LangVersion>preview</LangVersion>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <DoNotPublicize Include="tModLoader:Terraria.Tile" />
    <Publicize Include="CalamityMod" />
    <Publicize Include="FNA" IncludeCompilerGeneratedMembers="false" IncludeVirtualMembers="false" />
    <Publicize Include="ReLogic" IncludeCompilerGeneratedMembers="false" IncludeVirtualMembers="false" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Content\NPCs\KarkinosNPC\**" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="Content\NPCs\KarkinosNPC\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Content\NPCs\KarkinosNPC\**" />
  </ItemGroup>

  <ItemGroup>
    <LocalizationCompile Remove="Content\NPCs\KarkinosNPC\**" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Remove="Content\NPCs\KarkinosNPC\**" />
  </ItemGroup>

  <ItemGroup>
    <ShaderCompile Remove="Content\NPCs\KarkinosNPC\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Content\NPCs\KarkinosNPC\Karkinos.png" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Remove="Content\NPCs\KarkinosNPC\Karkinos.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Content\NPCs\KarkinosNPC\Karkinos.IK.Legs.cs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Content\NPCs\KarkinosNPC\Karkinos.cs" />
  </ItemGroup>


 
</Project>